import os
from django.conf.urls.defaults import *
from django.conf import settings
from models import Encuesta
 
info = {
         'queryset': Encuesta.objects.all(),
}

urlpatterns = patterns('fad-encuestas.encuestas.views',
    (r'^$', 'index'),
    (r'^ayuda/$', 'ayuda'),
    (r'^logout/$', 'logout_page'),
    (r'^sistema-agroforestal/$', 'sistemas_agroforestales'),
    (r'^sistema-agroforestal.pdf$', 'sistemas_agroforestales_pdf'),
    (r'^sistema-agroforestal.xls$', 'sistemas_agroforestales_xls'),
    (r'^descargar/xls-saf/$', 'hoja_calculo_saf_xls'),
    (r'^seguridad-alimentaria/$', 'seguridad_alimentaria'),
    (r'^seguridad-alimentaria.pdf$', 'seguridad_alimentaria_pdf'),
    (r'^seguridad-alimentaria.xls$', 'seguridad_alimentaria_xls'),
    (r'^descargar/xls-seguridad/$', 'hoja_calculo_seguridad_xls'),
    (r'^educacion/$', 'educacion'),
    (r'^educacion.pdf$', 'educacion_pdf'),
    (r'^educacion.xls$', 'educacion_xls'),
    (r'^descargar/xls-educacion/$', 'hoja_calculo_educacion_xls'),
    (r'^cobertura-boscosa/$', 'cobertura_boscosa'),
    (r'^cobertura-boscosa.pdf$', 'cobertura_boscosa_pdf'),
    (r'^cobertura-boscosa.xls$', 'cobertura_boscosa_xls'),
    (r'^descargar/xls-boscosa/$', 'hoja_calculo_boscosa_xls'),
    (r'^jovenes-en-poder/$', 'jovenes_en_poder'),
    (r'^finca/$', 'indicador1'),
    (r'^finca.pdf$', 'indicador1_pdf'),
    (r'^finca.xls$', 'indicador1_xls'),
    (r'^descargar/xls/$', 'hoja_calculo_indicador1_xls'),
    (r'^ingreso/$', 'indicador5'),
    (r'^ingreso.pdf$', 'indicador5_pdf'),
    (r'^ingreso.xls$', 'indicador5_xls'),
    (r'^descargar/xls-ingreso/$', 'hoja_calculo_ingreso_xls'),
    (r'^produccion/$', 'indicador4'),
    (r'^produccion.pdf$', 'indicador4_pdf'),
    (r'^produccion.xls$', 'indicador4_xls'),
     (r'^descargar/xls-produccion/$', 'hoja_calculo_produccion_xls'),
    (r'^grafos/$', 'grafos'),
    (r'^grafos/tipo-de-casa$', 'grafo_tipo_de_casa'),
    (r'^grafos/fuente-de-agua$', 'grafo_fuente_de_agua'),
    (r'^grafos/legalidad-propiedad$', 'grafo_legalidad_propiedad'),
    (r'^grafos/dueno-propiedad$', 'grafo_dueno_propiedad'),
    (r'^grafos/aquien-vendio$', 'grafo_a_vendio'),
    (r'^grafos/maneja-negocio$', 'grafo_maneja_negocio'),
    (r'^grafos/toma-decision$', 'grafo_desicion'),
    (r'^credito/credito$', 'grafo_credito'),
    (r'^credito/uso$', 'grafo_credito_uso'),
    (r'^credito/$', 'graph'),
    (r'^decision/$', 'tomar_decicion'),
    (r'^ajax/municipio/(?P<departamento>\d+)/$', 'get_municipios'),
    (r'^ajax/comunidad/(?P<municipio>\d+)/$', 'get_comunidad'),
    (r'^ajax/productor/$', 'productor_autocomplete'),
    (r'^buscar/$', 'buscar'),
)

